### ISSUE TITLE
Project configuration not working

### ISSUE THREAD

**Issue by helloeveryone404** [sleroy/sonar-slack-notifier-plugin#7]
Hi.  I've installed version 2.6 of the plugin for sonar version 7.9.  it sends messages when i use the webhook in the global settings but doesn't when i use that or any webhook in the project section.  I see in the documentation that there are no project level settings but i see in another thread where you commented: 'The plugin configuration is normally found in the project settings and the administration section.'  is this the case?  i do not see the plugin at the project level and therefore can't configure in the project settings.  if this isn't the cause, any advice on what could be the issue would be appreciated.  Thank you

**Comment by sleroy** [comment]
Sorry to haven't answer you in the meanwhile. 

I am rather busy and fixing the issues on the plugin is in "low priority" unless there is donation or a P/R that I may check and integrate.

The plugin has only been tested for JDK 11 and SonarQube 8 and higher.

I am not maintaining the lower versions. 

Thank you.

Sylvain
